### ISSUE TITLE
Bug: Previewing theme -> Theme Options -> Typography

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#66] opened 2019-07-29 11:56 UTC
1. Another theme is active.
2. Upload Gridd and click to preview.
3. Select: Theme Options -> Typography.
4. Click the back arrow icon. There is no response. One is not able to go one step back and either has to Activate & Publish or X out of the customizer.
(All the other sections below it such as Grid, Header, Content, Footer, Mobile Navigation and Theme Features one is able to click the back arrow to go one step back.)

<img width="300" alt="Screen Shot 2019-07-29 at 13 53 46" src="https://user-images.githubusercontent.com/5323259/62046558-86a5b500-b208-11e9-9257-40e274f52fca.png">

**Comment by aristath** [comment] 2019-07-29 18:26
This one is going to be a bit difficult to fix, it's a combination of an issue in wp-core and Kirki.
The theme uses the Kirki framework for all its options, and the typography control gets googlefonts via ajax.
The problem is that wp-core doesn't allow an ajax call from a non-active theme.
I'm already working on a solution to this in the next version of Kirki but that may take a while, I don't have a fix right here and now for v1.1.12 of the theme.

**Comment by aristath** [comment] 2019-08-18 11:11
Closing this one as it has already been fixed in Kirki v4.0
When Kirki 4.0 is released this will be updated in the theme as well.

**Closed by aristath** 2019-08-18 11:11 UTC
