### ISSUE TITLE
Updated to 1.1.18 - layout changed

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#105] opened 2019-09-26 08:29 UTC
Hey Ari

I have the latest Grid theme 1.1.18 and noticed these changes:
<img width="1319" alt="Screen Shot 2019-09-26 at 10 24 23" src="https://user-images.githubusercontent.com/5323259/65671623-d9a0ba80-e047-11e9-941b-8aab7844d3d8.png">

The full header area is suddenly shorter, as can be seen above.

Footer:

<img width="1319" alt="Screen Shot 2019-09-26 at 10 25 17" src="https://user-images.githubusercontent.com/5323259/65671689-fa691000-e047-11e9-8c6d-a44010073ca7.png">

There are lines through the menu. 

There are two console errors:

<img width="1339" alt="Screen Shot 2019-09-26 at 10 26 48" src="https://user-images.githubusercontent.com/5323259/65671801-32705300-e048-11e9-9db5-656fc0143935.png">

I will need to backtrack to the version before this. Perhaps by installing WP Rollback and then selecting to rollback to last version.
EDIT: Rolling back to version 1.1.17 worked fine.

Ps
Version 1.1.17 had some gallery issues. As the gallery looked nice in the Gutenberg background but not in the frontend. I will give you access to the dev site. Which I have now rolled back to 1.1.17.

I went ahead and added a Duplicator clone of the site that can be used for testing of 1.1.18:
https://www.dropbox.com/sh/ntuz6b88zqs3qwg/AAAx5QpTzs7T2TiuNpR8-Fxxa?dl=0

Dev site: https://fragmentsofawalk.com
Uses the 1.1.17 version og Grid theme. I will give you login info on Slack.

**Comment by aristath** [comment] 2019-09-28 09:13
This actually ties into the discussion we had a few days ago on Slack about improving/fixing the default values for customizer settings so that when installing the theme it looks better and it doesn't require so much tweaking.
And I hope you can appreciate now why it has to be done in small steps... The reason this happened is because apparently you had not tweaked the value for a control whose default changed in v1.1.18.
As discussed on slack, the customizer only saves changed values, not all values for all settings. So the value for that setting was not stored in the database, and it just falls-back to using the default (which changed).
For v1.1.18 this was an inevitable side-effect.

It will not be fixed in the theme, you will have to update to 1.1.18 and then just go in the customizer and fix the value to be what you want it to be (if I'm not mistaken, looking at your screenshot I'd say you just need to tweak the header max-width).

The good news: 
This will ONLY happen for v1.1.18.
In v1.1.18 I included an [`Upgrade`](https://github.com/wplemon/gridd/blob/develop/inc/classes/Upgrade.php) class which will take care of these setting changes in future releases. Updating from a previous version to v1.1.18 will not automatically change the values to account for defaults changes - which is why this version only included a few changes instead of revamping everything. Updating from v1.1.18 to future versions however will take default value changes.

The bad news: 
Going from a version lower than 1.1.18 to a version higher than 1.1.18 can't properly change the default values. Going from 1.1.18 to a higher version will not have any issues. The problem is that the `Upgrade` class was introduced in this version so it can't properly run the upgrades and fix values unless it already exists in the version that was already installed (I hope that sentence makes sense...). The reason is that it uses a `gridd_version` setting which was added in v1.1.18, and stores the version of the theme. This setting is used by the `Upgrade` class to determine which upgrade tasks need to run.

Adding this class was an investment for the future so we can start fixing the way the theme looks without breaking existing sites. But in order for that to happen the site has to already be on v1.1.18... Which is why I have not released any updates for the theme in almost a month. I want to be sure that all sites (or at least the vast majority of sites using Gridd) have already updated their theme to v1.1.18 before I can improve the implementation of some things without causing any backwards-compatibility issues.

Marking this one as `wontfix` because it just can't be fixed for v1.1.18.

**Closed by aristath** 2019-09-28 09:13 UTC

**Comment by paaljoachim** [comment] 2019-09-29 13:22
Thank you for a very good explanation! Btw if/when someone posts in the support forum about something like this then you can just use some of your explanation for it.

When something is not correct I and anyone else can go into the customizer and check for anything that does not seem correct.

I noticed I had to change the Header Maximum Width from 45 rem. I changed it to 100%. That took care of the Header issue.

I am right now working on correcting the menu lines in the footer.
