### ISSUE TITLE
Using child theme hides instagram thumbnail images

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#147] opened 2019-11-07 03:05 UTC
Hey Ari

I got something weird here. In the footer there are 3 footer widgets.
1. Menu (which I styled to not create so much space between each link.)
2. Get a free sample text and image.
3. Instagram shortcode showing images.
4. Facebook like box.

Having Gridd theme active this is seen:

![Screen Shot 2019-11-06 at 21 56 31](https://user-images.githubusercontent.com/5323259/68356428-5495d000-00e0-11ea-99fc-a2156279792f.png)

(I have to go to the themes screen to switch themes as the customizer is acting up again. It seems it has to do with Gridd plus version 1.0.7.)

Having a Gridd child theme active this is seen:
![Screen Shot 2019-11-06 at 21 58 06](https://user-images.githubusercontent.com/5323259/68356568-a0487980-00e0-11ea-835b-84b06a7cde67.png)

Deleting all the styles I have inside style.css this is seen:
![Screen Shot 2019-11-06 at 21 59 51](https://user-images.githubusercontent.com/5323259/68356691-fb7a6c00-00e0-11ea-9dca-b38aee1c7def.png)

I remove the code I placed into the child theme functions file and this is the only code that remains:

```
<?php

// Enqueue parent styles and load child styles.
// https://developer.wordpress.org/themes/advanced-topics/child-themes/
add_action( 'wp_enqueue_scripts', 'my_theme_enqueue_styles' );
function my_theme_enqueue_styles() {
 
    $parent_style = 'parent-style'; // This is style for the Gridd theme.
 
    wp_enqueue_style( $parent_style, get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array( $parent_style ),
        wp_get_theme()->get('Version')
    );
}

```

Switching to Twenty Nineteen default theme I see the Instagram images.

I am puzzled and right now do not know what to do with it. I am wondering if there is some other code that I need to add to the child theme functions file.

**Comment by paaljoachim** [comment] 2019-11-08 21:27
I am updating this issue.

As seen in the footer:
![Screen Shot 2019-11-08 at 16 22 59](https://user-images.githubusercontent.com/5323259/68511525-292bf600-0244-11ea-92b0-c2a6bb67cec6.png)

Widgets screen:
![Screen Shot 2019-11-08 at 16 25 40](https://user-images.githubusercontent.com/5323259/68511666-74de9f80-0244-11ea-97d6-2c4e7770eb0c.png)


Moving the Facebook and Instagram widgets into the offcanvas sidebar:
![Screen Shot 2019-11-08 at 16 26 37](https://user-images.githubusercontent.com/5323259/68511740-96d82200-0244-11ea-94ff-b38e7dce5df3.png)

**Comment by aristath** [comment] 2019-11-09 15:16
Closing this one, it was caused by a deferred footer. The widget was trying to run JS and get images from the instagram API before the widget was loaded

**Closed by aristath** 2019-11-09 15:16 UTC

**Comment by paaljoachim** [comment] 2019-11-09 15:28
Thanks Ari!

**Comment by paaljoachim** [comment] 2019-11-11 01:38
I am going to add in the following information as I am going to share this issue with the developer of the Facebook Like Box and Instagram plugins. As hopefully this is something they can fix for the next version of both the plugins.

Ari you mentioned this for me on Slack:

Deferring works fine 99.9% of the time. In this case, the instagram widget was getting some things using ajax, and things got messy.
On page-load it was trying to get instagram and then put its contents in the footer. But when it did that the footer didn't exist yet, so it didn't know where to put the images.
That's why it was working on anything but the footer.

It's really just an edge case. The JS for the widget should ideally be loaded with the widget itself. In this case it wasn't and that's what was causing the issue.

**Comment by aristath** [comment] 2019-11-11 19:33
I don't think it's going to be an easy fix... They have to put the JS somewhere, and the were not doing anything wrong.
What they _could_ do however, is trigger a JS event when the element gets rendered, and then add a listener in the script that will run the needed scripts.

But yeah... it's an extreme edge-case. Content usually gets loaded along with the page's HTML. The HTML _usually_ comes first, and then the JS can run with it. When deferring the footer-load, the content loads later and that's what makes this weird.

**Comment by paaljoachim** [comment] 2019-11-13 03:01
Support gave me this link: https://smashballoon.com/my-photos-dont-show-up-sometimes-unless-i-refresh-my-page-ajax-theme/

I tried it out but it made no difference. I went into the settings and noticed a lot of options in there.
