### ISSUE TITLE
Not able to add widget to new widget area in header

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#89] opened 2019-08-21 08:23 UTC
I added another widget area in the header:

![Screen Shot 2019-08-21 at 10 16 14](https://user-images.githubusercontent.com/5323259/63414761-c8d3a800-c3fc-11e9-9262-2c532b6db453.png)

Went to add a widget. I also tried the new experimental Gutenberg widgets. 
In the regular widget screen I am not able to add any widget.
![Screen Shot 2019-08-21 at 10 17 46](https://user-images.githubusercontent.com/5323259/63414850-f7ea1980-c3fc-11e9-9ca2-4fbccae354da.png)

(I have not tried to deactivate any of the plugins, and have a few active along with the Gutenberg plugin.)

I opened the Inspect console and noticed a bunch of errors listed.
Each time I clicked to add a widget another error showed up.

![Screen Shot 2019-08-21 at 10 21 05](https://user-images.githubusercontent.com/5323259/63415183-9bd3c500-c3fd-11e9-8d6f-3b1c265a2cce.png)

Uncaught TypeError: b(...).slice is not a function
    at Function.<anonymous> (load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2)
    at Function.<anonymous> (VM2030 customize-base.min.js:1)
    at Function.each (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.2:2)
    at Function.each (VM2030 customize-base.min.js:1)
    at f.addWidget (load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2)
    at N.d.submit (load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2)
    at N.d._submit (load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2)
    at HTMLDivElement.dispatch (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.2:3)
    at HTMLDivElement.r.handle (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.2:3)
(anonymous) @ load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2
(anonymous) @ VM2030 customize-base.min.js:1
each @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.2:2
each @ VM2030 customize-base.min.js:1
addWidget @ load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2
submit @ load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2
_submit @ load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2
dispatch @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.2:3
r.handle @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.2:3

**Comment by carolinan** [comment] 2019-08-25 03:53
I was trying to see if I could reproduce this.

Attempt 1: Without Gutenberg installed.
 After adding the widget areas to the header, I select a widget area and click the cogwheel, the option panel expands, but when I click on the button that says:
"Click here to edit your widgets", nothing happens.
![edit-widget-1](https://user-images.githubusercontent.com/7422055/63645187-c755f880-c6f8-11e9-9b4c-f25ad4c961aa.png)

I tried a couple of more times, and apparently, publishing was not enough,
I also had to **refresh** the page first.
-Once I could access the panel, there were no errors when adding, editing, removing or saving widgets.

Attempt 2: With Gutenberg Version 6.3.0 installed.
I can add and remove widgets -until I try to save my changes:, where I receive the error message:
_Unable to save due to 1 invalid setting._

There are no console errors.
Note that I can not save changes to any of the widget areas, including the default footer widget areas.

Attempt 3: 
I reset my WordPress install, and reactivated Gridd.
I was able to reproduce the problem from attempt one: even after publishing the changes, I have to refresh the page to be able to edit the widgets.

Attempt 4:
I reset my WordPress install, and reactivated Gridd and Gutenberg Version 6.3.0.
This time, I ran into a different problem.
After adding a widget area to the header grid, I pressed "Publish" and received the message:
_Unable to save due to 12 invalid settings._
-There are no console errors.

**Comment by aristath** [comment] 2019-08-25 15:45
Meh I found what the issue is here...
The header grid uses a prtial-refresh and `postMessage`. As a result the preview doesn't get a full refresh and the parent frame (the customizer) can't detect the new sidebar - and therefore it doesn't activate the section.
Fixed by removing the partial refresh.
@paaljoachim @carolinan thank you both for all the details you provided! <3

**Closed** 2019-08-25 15:44 UTC

**Comment by paaljoachim** [comment] 2019-08-29 15:49
Nb!
I have version 1.1.17 installed.

Gutenberg plugin installed along with a lot of other plugins.

There are problems with adding another widget in the footer.
<img width="1140" alt="Screen Shot 2019-08-29 at 17 48 38" src="https://user-images.githubusercontent.com/5323259/63955607-45155d80-ca85-11e9-9faa-653c0bd9e481.png">

Console errors:
Failed to load resource: the server responded with a status of 404 ()
text-widgets.min.js?ver=5.2.2:1 Uncaught TypeError: wp.editor.initialize is not a function
    at c (text-widgets.min.js?ver=5.2.2:1)
    at N.d.initializeEditor (text-widgets.min.js?ver=5.2.2:1)
    at i (text-widgets.min.js?ver=5.2.2:1)
5load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2 Uncaught TypeError: b(...).slice is not a function
    at Function.<anonymous> (load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2)
    at Function.<anonymous> (customize-base.min.js?ver=5.2.2:1)
    at Function.each (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.2:2)
    at Function.each (customize-base.min.js?ver=5.2.2:1)
    at f.addWidget (load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2)
    at N.d.submit (load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2)
    at N.d._submit (load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2)
    at HTMLDivElement.dispatch (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.2:3)
    at HTMLDivElement.r.handle (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.2:3)
jquery-migrate.min.js?ver=1.4.1:2 JQMIGRATE: Migrate is installed, version 1.4.1
VM12020:1 LayerSlider initialized | core: 6.9.0-stable | WP Plugin: 6.9.1
VM12020:1 Find updates and docs @ https://layerslider.kreaturamedia.com/
skin.css:1 Failed to load resource: the server responded with a status of 404 ()
load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2 Uncaught TypeError: b(...).slice is not a function
    at Function.<anonymous> (load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2)
    at Function.<anonymous> (customize-base.min.js?ver=5.2.2:1)
    at Function.each (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.2:2)
    at Function.each (customize-base.min.js?ver=5.2.2:1)
    at f.addWidget (load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2)
    at N.d.submit (load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2)
    at N.d._submit (load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2)
    at HTMLDivElement.dispatch (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.2:3)
    at HTMLDivElement.r.handle (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.2:3)
skin.css:1 Failed to load resource: the server responded with a status of 404 ()
sb-instagram.min.js?ver=1.12.2:1 Uncaught TypeError: Cannot read property 'minRes' of undefined
    at HTMLDivElement.<anonymous> (sb-instagram.min.js?ver=1.12.2:1)
    at Function.each (jquery.js?ver=1.12.4-wp:2)
    at a.fn.init.each (jquery.js?ver=1.12.4-wp:2)
    at sb-instagram.min.js?ver=1.12.2:1
(anonymous) @ sb-instagram.min.js?ver=1.12.2:1
each @ jquery.js?ver=1.12.4-wp:2
each @ jquery.js?ver=1.12.4-wp:2
(anonymous) @ sb-instagram.min.js?ver=1.12.2:1
2sb-instagram.min.js?ver=1.12.2:1 Uncaught TypeError: Cannot read property 'minRes' of undefined
    at HTMLDivElement.<anonymous> (sb-instagram.min.js?ver=1.12.2:1)
    at Function.each (jquery.js?ver=1.12.4-wp:2)
    at a.fn.init.each (jquery.js?ver=1.12.4-wp:2)
    at sb-instagram.min.js?ver=1.12.2:1
(anonymous) @ sb-instagram.min.js?ver=1.12.2:1
each @ jquery.js?ver=1.12.4-wp:2
each @ jquery.js?ver=1.12.4-wp:2
(anonymous) @ sb-instagram.min.js?ver=1.12.2:1
setTimeout (async)
j @ sb-instagram.min.js?ver=1.12.2:1
(anonymous) @ sb-instagram.min.js?ver=1.12.2:1
dispatch @ jquery.js?ver=1.12.4-wp:3
r.handle @ jquery.js?ver=1.12.4-wp:3
load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2 Uncaught TypeError: b(...).slice is not a function
    at Function.<anonymous> (load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2)
    at Function.<anonymous> (customize-base.min.js?ver=5.2.2:1)
    at Function.each (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.2:2)
    at Function.each (customize-base.min.js?ver=5.2.2:1)
    at f.addWidget (load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2)
    at N.d.submit (load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2)
    at N.d._submit (load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2)
    at HTMLDivElement.dispatch (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.2:3)
    at HTMLDivElement.r.handle (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.2:3)
(anonymous) @ load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2
(anonymous) @ customize-base.min.js?ver=5.2.2:1
each @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.2:2
each @ customize-base.min.js?ver=5.2.2:1
addWidget @ load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2
submit @ load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2
_submit @ load-scripts.php?c=1&load[]=heartbeat,customize-widgets,hoverIntent,accordion,customize-nav-menus,imgareaselect,customize-models,customize-views,mce-view,im&load[]=age-edit&ver=5.2.2:2
dispatch @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.2:3
r.handle @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.2:3
sb-instagram.min.js?ver=1.12.2:1 Uncaught TypeError: Cannot read property 'minRes' of undefined
    at HTMLDivElement.<anonymous> (sb-instagram.min.js?ver=1.12.2:1)
    at Function.each (jquery.js?ver=1.12.4-wp:2)
    at a.fn.init.each (jquery.js?ver=1.12.4-wp:2)
    at sb-instagram.min.js?ver=1.12.2:1
(anonymous) @ sb-instagram.min.js?ver=1.12.2:1
each @ jquery.js?ver=1.12.4-wp:2
each @ jquery.js?ver=1.12.4-wp:2
(anonymous) @ sb-instagram.min.js?ver=1.12.2:1
setTimeout (async)
j @ sb-instagram.min.js?ver=1.12.2:1
(anonymous) @ sb-instagram.min.js?ver=1.12.2:1
dispatch @ jquery.js?ver=1.12.4-wp:3
r.handle @ jquery.js?ver=1.12.4-wp:3

**Comment by paaljoachim** [comment] 2019-08-30 10:50
I turned off all plugins and cleared the cache and I am still not able to add widgets to the footer. Here is the error I see:

Uncaught TypeError: Cannot read property 'slice' of null
    at Function.<anonymous> (customize-widgets.min.js?ver=5.2.2:1)
    at Function.<anonymous> (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,customize-base,wp-a11y,wp-util,jquery-ui-core,customize-controls,jquery-ui-widget,jquery-u&load[]=i-mouse,jquery-ui-sortable,jquery-ui-draggable,jquery-ui-droppable,backbone,wp-backbone,wp-ajax-response,jquery-color,wp-lists,p&load[]=ostbox,nav-menu,jquery-ui-slider,jquery-touch-punch,iris,wp-color-picker,jquery-ui-button,jquery-ui-datepicker,shortcode,utils,m&load[]=edia-models,moxiejs,plupload,wp-plupload&ver=5.2.2:10)
    at Function.each (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,customize-base,wp-a11y,wp-util,jquery-ui-core,customize-controls,jquery-ui-widget,jquery-u&load[]=i-mouse,jquery-ui-sortable,jquery-ui-draggable,jquery-ui-droppable,backbone,wp-backbone,wp-ajax-response,jquery-color,wp-lists,p&load[]=ostbox,nav-menu,jquery-ui-slider,jquery-touch-punch,iris,wp-color-picker,jquery-ui-button,jquery-ui-datepicker,shortcode,utils,m&load[]=edia-models,moxiejs,plupload,wp-plupload&ver=5.2.2:2)
    at Function.each (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,customize-base,wp-a11y,wp-util,jquery-ui-core,customize-controls,jquery-ui-widget,jquery-u&load[]=i-mouse,jquery-ui-sortable,jquery-ui-draggable,jquery-ui-droppable,backbone,wp-backbone,wp-ajax-response,jquery-color,wp-lists,p&load[]=ostbox,nav-menu,jquery-ui-slider,jquery-touch-punch,iris,wp-color-picker,jquery-ui-button,jquery-ui-datepicker,shortcode,utils,m&load[]=edia-models,moxiejs,plupload,wp-plupload&ver=5.2.2:10)
    at f.addWidget (customize-widgets.min.js?ver=5.2.2:1)
    at N.d.submit (customize-widgets.min.js?ver=5.2.2:1)
    at N.d._submit (customize-widgets.min.js?ver=5.2.2:1)
    at HTMLDivElement.dispatch (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,customize-base,wp-a11y,wp-util,jquery-ui-core,customize-controls,jquery-ui-widget,jquery-u&load[]=i-mouse,jquery-ui-sortable,jquery-ui-draggable,jquery-ui-droppable,backbone,wp-backbone,wp-ajax-response,jquery-color,wp-lists,p&load[]=ostbox,nav-menu,jquery-ui-slider,jquery-touch-punch,iris,wp-color-picker,jquery-ui-button,jquery-ui-datepicker,shortcode,utils,m&load[]=edia-models,moxiejs,plupload,wp-plupload&ver=5.2.2:3)
    at HTMLDivElement.r.handle (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,underscore,customize-base,wp-a11y,wp-util,jquery-ui-core,customize-controls,jquery-ui-widget,jquery-u&load[]=i-mouse,jquery-ui-sortable,jquery-ui-draggable,jquery-ui-droppable,backbone,wp-backbone,wp-ajax-response,jquery-color,wp-lists,p&load[]=ostbox,nav-menu,jquery-ui-slider,jquery-touch-punch,iris,wp-color-picker,jquery-ui-button,jquery-ui-datepicker,shortcode,utils,m&load[]=edia-models,moxiejs,plupload,wp-plupload&ver=5.2.2:3)


<img width="1367" alt="Screen Shot 2019-08-30 at 12 50 40" src="https://user-images.githubusercontent.com/5323259/64015417-cbcd4780-cb24-11e9-9d7f-9cf654800756.png">
